# http interface is not tested
http_options:
  host: 0.0.0.0  # or specify a particular IP to bind the HTTP server to
  port: 8000      # HTTP port for serving

applications:
  - name: unifit_inference_worker
    route_prefix: /
    import_path: unifit_inference_worker:unifit_inference
    runtime_env: {}

