grpc_options:
  port: 9000
  grpc_servicer_functions:
    - gliner_protos_pb2_grpc.add_GlinerServicer_to_server

# # http interface is not tested
# http_options:
#   host: 0.0.0.0  # or specify a particular IP to bind the HTTP server to
#   port: 8000      # HTTP port for serving
#   http_servicer_functions:
#     - gliner_protos_pb2_grpc.add_GlinerServicer_to_server

applications:
  - name: gliner
    route_prefix: /gliner
    import_path: gliner_server:g
    runtime_env: {}
    deployments:
      - name: static_gliner
        num_replicas: 10
        max_concurrent_queries: 100

